[project]
name = "backend"
version = "0.1.0"
description = "Facto - AI fact checker backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "openai>=1.76.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
